#!/usr/bin/env python3
"""Build the single-file MxNM Lung montage field test."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from scripts.build_report_image_caption_diagnostic import (
        DIRECTIVES,
        prepare_component,
        read_component,
    )
except ModuleNotFoundError:
    from build_report_image_caption_diagnostic import (
        DIRECTIVES,
        prepare_component,
        read_component,
    )


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "tests"
    / "windows"
    / "generated"
    / "mxnm_montage_lung_field_test_standalone.ahk"
)

COMPONENTS = (
    "src/Lib/UIA.ahk",
    "tests/windows/mxnm_montage_lung_field_test.ahk",
)


def build_field_test_text(root: Path = ROOT) -> str:
    parts = [
        "; Generated single-file Windows field test.",
        "; Edit source components and rebuild; do not edit this file.",
        "; Operator-stepped Lung montage test; one action per hotkey.",
        ";@Ahk2Exe-SetFileVersion 0.3.0.0",
        ";@Ahk2Exe-SetProductVersion 0.3.0",
        ";@Ahk2Exe-SetName MxNM Montage Lung Field Test",
        "",
        *DIRECTIVES,
        "",
    ]
    for relative_path in COMPONENTS:
        path = root / relative_path
        if not path.is_file():
            raise FileNotFoundError(f"Missing field-test component: {path}")
        parts.extend(
            (
                f"; --- BEGIN {relative_path} ---",
                prepare_component(read_component(path), relative_path),
                f"; --- END {relative_path} ---",
                "",
            )
        )
    result = "\n".join(parts).rstrip() + "\n"
    if "\ufeff" in result:
        raise ValueError("Generated field test contains embedded U+FEFF")
    if any(
        line.lstrip().lower().startswith("#include")
        for line in result.splitlines()
    ):
        raise ValueError("Generated field test still contains #Include")
    return result


def write_field_test(output: Path = OUTPUT) -> None:
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_field_test_text(), encoding="utf-8")
    print(f"Wrote {output}")
    print(f"Size: {output.stat().st_size} bytes")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the standalone MxNM Lung montage field test."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help="Destination for the generated standalone AHK field test.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    write_field_test(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
