#!/usr/bin/env python3
"""Build the single-file Windows harness for adaptive Viewer checkpoint 1."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from scripts import ahk_bundle
except ModuleNotFoundError:  # executed directly from scripts/
    import ahk_bundle


ROOT = ahk_bundle.ROOT
DIRECTIVES = ahk_bundle.HARNESS_DIRECTIVES
read_component = ahk_bundle.read_component
OUTPUT = ROOT / "tests/windows/generated/mxnm_viewer_adaptive_checkpoint1_standalone.ahk"

COMPONENTS = (
    "src/core/win32_window.ahk",
    "src/mxnm_config_geometry_provider.ahk",
    "src/mxnm_viewer_tool_commands.ahk",
    "src/mxnm_measurement_target_resolver.ahk",
    "src/mxnm_viewer_runtime_probe.ahk",
    "tests/windows/mxnm_viewer_adaptive_checkpoint1.ahk",
)

HEADER = (
    '; Generated single-file field harness.',
    '; Edit the source components and rebuild; do not edit this file.',
    '; Interaction policy: read-only HWND/config audit.',
    ';@Ahk2Exe-SetFileVersion 0.0.1.2',
    ';@Ahk2Exe-SetProductVersion 0.0.1',
    ';@Ahk2Exe-SetName MxNM Viewer Adaptive Checkpoint 1',
)


def viewer_tool_probe_subset(text: str) -> str:
    """Keep the tool model, config plan and point mapping; drop dispatch code."""
    provider_marker = "class MxNMViewerToolCommandProvider {"
    plan_marker = "BuildMxNMViewerToolCommandPlan(viewerExe, configPaths) {"
    result_marker = "MakeMxNMViewerToolResult(ok, code) {"
    mapping_marker = "MapMxNMViewerToolPadOriginToRuntimeFrame("
    target_marker = "DispatchMxNMViewerToolButton("
    for marker in (
        provider_marker,
        plan_marker,
        result_marker,
        mapping_marker,
        target_marker,
    ):
        if marker not in text:
            raise ValueError(f"Viewer tool probe marker was not found: {marker}")
    model_section = text.split(provider_marker, 1)[0].rstrip()
    plan_section = (
        plan_marker
        + text.split(plan_marker, 1)[1].split(result_marker, 1)[0]
    ).rstrip()
    after_result = text.split(result_marker, 1)[1]
    mapping_section = (
        mapping_marker
        + after_result.split(mapping_marker, 1)[1].split(
            target_marker,
            1,
        )[0]
    ).rstrip()
    return (
        model_section + "\n\n" + plan_section + "\n\n" + mapping_section + "\n"
    )


def _probe_subset(text: str, relative_path: str) -> str:
    if relative_path == "src/mxnm_viewer_tool_commands.ahk":
        return viewer_tool_probe_subset(text)
    return text


def prepare_component(text: str, relative_path: str) -> str:
    """Compatibility helper for other builders: subset then strip."""
    return ahk_bundle.strip_includes_and_directives(
        _probe_subset(text, relative_path), DIRECTIVES
    )


def build_checkpoint_text(root: Path = ROOT) -> str:
    return ahk_bundle.bundle(
        HEADER,
        COMPONENTS,
        root=root,
        transform=_probe_subset,
        label="checkpoint",
        missing_message="Missing checkpoint component",
    )


def write_checkpoint(output: Path = OUTPUT) -> None:
    ahk_bundle.write_bundle(build_checkpoint_text(), output)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the standalone Viewer checkpoint AHK.")
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help="Destination for the generated standalone AHK.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    write_checkpoint(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
