#!/usr/bin/env python3
"""Build the single-file report image caption migration diagnostic."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from scripts.build_mxnm_viewer_adaptive_checkpoint import (
        DIRECTIVES,
        read_component,
    )
except ModuleNotFoundError:
    from build_mxnm_viewer_adaptive_checkpoint import (
        DIRECTIVES,
        read_component,
    )


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "tests"
    / "windows"
    / "generated"
    / "report_image_caption_migration_diagnostic_standalone.ahk"
)

COMPONENTS = (
    "src/Lib/UIA.ahk",
    "tests/windows/report_image_caption_migration_diagnostic.ahk",
)

UIA_STANDALONE_ENTRYPOINT = (
    "if !A_IsCompiled && A_LineFile = A_ScriptFullPath\n"
    "    UIA.Viewer()\n"
)


def prepare_component(text: str, relative_path: str) -> str:
    if relative_path == "src/Lib/UIA.ahk":
        if UIA_STANDALONE_ENTRYPOINT not in text:
            raise ValueError("UIA standalone entrypoint was not found")
        text = text.replace(UIA_STANDALONE_ENTRYPOINT, "", 1)

    directives = {directive.lower() for directive in DIRECTIVES}
    lines: list[str] = []
    for line in text.splitlines():
        normalized = line.strip().lower()
        if line.lstrip().lower().startswith("#include"):
            continue
        if normalized in directives:
            continue
        lines.append(line.rstrip())
    return "\n".join(lines).strip() + "\n"


def build_diagnostic_text(root: Path = ROOT) -> str:
    parts = [
        "; Generated single-file field diagnostic.",
        "; Edit the source components and rebuild; do not edit this file.",
        "; Does not click, paste, scroll, activate another window, or persist copied text.",
        ";@Ahk2Exe-SetFileVersion 1.1.0.0",
        ";@Ahk2Exe-SetProductVersion 1.1.0",
        ";@Ahk2Exe-SetName MedEx Report Image Caption Diagnostic",
        "",
        *DIRECTIVES,
        "",
    ]
    for relative_path in COMPONENTS:
        path = root / relative_path
        if not path.is_file():
            raise FileNotFoundError(f"Missing diagnostic component: {path}")
        parts.extend(
            (
                f"; --- BEGIN {relative_path} ---",
                prepare_component(read_component(path), relative_path),
                f"; --- END {relative_path} ---",
                "",
            )
        )
    result = "\n".join(parts).rstrip() + "\n"
    if "\ufeff" in result:
        raise ValueError("Generated diagnostic contains an embedded U+FEFF")
    if any(
        line.lstrip().lower().startswith("#include")
        for line in result.splitlines()
    ):
        raise ValueError("Generated diagnostic still contains #Include")
    return result


def write_diagnostic(output: Path = OUTPUT) -> None:
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_diagnostic_text(), encoding="utf-8")
    print(f"Wrote {output}")
    print(f"Size: {output.stat().st_size} bytes")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the standalone report image caption diagnostic."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help="Destination for the generated standalone diagnostic AHK.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    write_diagnostic(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
