#!/usr/bin/env python3
"""Build the single-file Viewer context-menu receiver diagnostic."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from scripts.build_mxnm_viewer_adaptive_checkpoint import (
        DIRECTIVES,
        prepare_component,
        read_component,
    )
except ModuleNotFoundError:
    from build_mxnm_viewer_adaptive_checkpoint import (
        DIRECTIVES,
        prepare_component,
        read_component,
    )


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "tests"
    / "windows"
    / "generated"
    / "mxnm_context_menu_receiver_diagnostic_standalone.ahk"
)

COMPONENTS = (
    "src/measurement_model.ahk",
    "src/mxnm_config_geometry_provider.ahk",
    "src/mxnm_viewer_tool_commands.ahk",
    "src/mxnm_measurement_target_resolver.ahk",
    "src/mxnm_context_target_session.ahk",
    "tests/windows/mxnm_context_menu_receiver_diagnostic.ahk",
)


def build_diagnostic_text(root: Path = ROOT) -> str:
    parts = [
        "; Generated single-file field diagnostic.",
        "; Edit the source components and rebuild; do not edit this file.",
        "; Opens and closes context popups; never invokes a menu command.",
        ";@Ahk2Exe-SetFileVersion 0.0.1.0",
        ";@Ahk2Exe-SetProductVersion 0.0.1",
        ";@Ahk2Exe-SetName MxNM Viewer Context Diagnostic",
        "",
        *DIRECTIVES,
        "",
    ]
    for relative_path in COMPONENTS:
        path = root / relative_path
        if not path.is_file():
            raise FileNotFoundError(f"Missing diagnostic component: {path}")
        parts.extend(
            (
                f"; --- BEGIN {relative_path} ---",
                prepare_component(read_component(path), relative_path),
                f"; --- END {relative_path} ---",
                "",
            )
        )
    result = "\n".join(parts).rstrip() + "\n"
    if "\ufeff" in result:
        raise ValueError("Generated diagnostic contains an embedded U+FEFF")
    if any(
        line.lstrip().lower().startswith("#include")
        for line in result.splitlines()
    ):
        raise ValueError("Generated diagnostic still contains #Include")
    return result


def write_diagnostic(output: Path = OUTPUT) -> None:
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_diagnostic_text(), encoding="utf-8")
    print(f"Wrote {output}")
    print(f"Size: {output.stat().st_size} bytes")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the standalone Viewer context diagnostic."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help="Destination for the generated standalone diagnostic AHK.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    write_diagnostic(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
