#!/usr/bin/env python3
"""Build the single-file Windows harness for adaptive Viewer checkpoint 1."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "tests"
    / "windows"
    / "generated"
    / "mxnm_viewer_adaptive_checkpoint1_standalone.ahk"
)

COMPONENTS = (
    "src/mxnm_config_geometry_provider.ahk",
    "src/mxnm_viewer_tool_commands.ahk",
    "src/mxnm_measurement_target_resolver.ahk",
    "src/mxnm_viewer_runtime_probe.ahk",
    "tests/windows/mxnm_viewer_adaptive_checkpoint1.ahk",
)

DIRECTIVES = (
    "#Requires AutoHotkey v2.0",
    "#SingleInstance Force",
    "#Warn",
)


def read_component(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    return text[1:] if text.startswith("\ufeff") else text


def viewer_tool_probe_subset(text: str) -> str:
    provider_marker = "class MxNMViewerToolCommandProvider {"
    plan_marker = "BuildMxNMViewerToolCommandPlan(viewerExe, configPaths) {"
    result_marker = "MakeMxNMViewerToolResult(ok, code) {"
    mapping_marker = "MapMxNMViewerToolPadOriginToRuntimeFrame("
    target_marker = "DispatchMxNMViewerToolButton("
    for marker in (
        provider_marker,
        plan_marker,
        result_marker,
        mapping_marker,
        target_marker,
    ):
        if marker not in text:
            raise ValueError(f"Viewer tool probe marker was not found: {marker}")
    model_section = text.split(provider_marker, 1)[0].rstrip()
    plan_section = (
        plan_marker
        + text.split(plan_marker, 1)[1].split(result_marker, 1)[0]
    ).rstrip()
    after_result = text.split(result_marker, 1)[1]
    mapping_section = (
        mapping_marker
        + after_result.split(mapping_marker, 1)[1].split(
            target_marker,
            1,
        )[0]
    ).rstrip()
    return (
        model_section + "\n\n" + plan_section + "\n\n" + mapping_section + "\n"
    )


def prepare_component(text: str, relative_path: str) -> str:
    if relative_path == "src/mxnm_viewer_tool_commands.ahk":
        text = viewer_tool_probe_subset(text)
    lines: list[str] = []
    directives = {directive.lower() for directive in DIRECTIVES}
    for line in text.splitlines():
        normalized = line.strip().lower()
        if line.lstrip().lower().startswith("#include"):
            continue
        if normalized in directives:
            continue
        lines.append(line.rstrip())
    return "\n".join(lines).strip() + "\n"


def build_checkpoint_text(root: Path = ROOT) -> str:
    parts = [
        "; Generated single-file field harness.",
        "; Edit the source components and rebuild; do not edit this file.",
        "; Interaction policy: read-only HWND/config audit.",
        ";@Ahk2Exe-SetFileVersion 0.0.1.2",
        ";@Ahk2Exe-SetProductVersion 0.0.1",
        ";@Ahk2Exe-SetName MxNM Viewer Adaptive Checkpoint 1",
        "",
        *DIRECTIVES,
        "",
    ]
    for relative_path in COMPONENTS:
        path = root / relative_path
        if not path.is_file():
            raise FileNotFoundError(f"Missing checkpoint component: {path}")
        parts.extend(
            (
                f"; --- BEGIN {relative_path} ---",
                prepare_component(read_component(path), relative_path),
                f"; --- END {relative_path} ---",
                "",
            )
        )
    result = "\n".join(parts).rstrip() + "\n"
    if "\ufeff" in result:
        raise ValueError("Generated checkpoint contains an embedded U+FEFF")
    if any(
        line.lstrip().lower().startswith("#include")
        for line in result.splitlines()
    ):
        raise ValueError("Generated checkpoint still contains #Include")
    return result


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_checkpoint_text(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    print(f"Size: {OUTPUT.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
