#!/usr/bin/env python3
"""Build the single-file Viewer context-menu receiver diagnostic."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from scripts import ahk_bundle
except ModuleNotFoundError:  # executed directly from scripts/
    import ahk_bundle


ROOT = ahk_bundle.ROOT
DIRECTIVES = ahk_bundle.HARNESS_DIRECTIVES
read_component = ahk_bundle.read_component
OUTPUT = ROOT / "tests/windows/generated/mxnm_context_menu_receiver_diagnostic_standalone.ahk"

COMPONENTS = (
    "src/core/win32_window.ahk",
    "src/measurement_model.ahk",
    "src/mxnm_config_geometry_provider.ahk",
    "src/mxnm_viewer_tool_commands.ahk",
    "src/mxnm_measurement_target_resolver.ahk",
    "src/mxnm_context_target_session.ahk",
    "tests/windows/mxnm_context_menu_receiver_diagnostic.ahk",
)

HEADER = (
    '; Generated single-file field diagnostic.',
    '; Edit the source components and rebuild; do not edit this file.',
    '; Opens and closes context popups; never invokes a menu command.',
    ';@Ahk2Exe-SetFileVersion 0.0.1.0',
    ';@Ahk2Exe-SetProductVersion 0.0.1',
    ';@Ahk2Exe-SetName MxNM Viewer Context Diagnostic',
)

try:
    from scripts.build_mxnm_viewer_adaptive_checkpoint import _probe_subset
except ModuleNotFoundError:
    from build_mxnm_viewer_adaptive_checkpoint import _probe_subset


def build_diagnostic_text(root: Path = ROOT) -> str:
    return ahk_bundle.bundle(
        HEADER,
        COMPONENTS,
        root=root,
        transform=_probe_subset,
        label="diagnostic",
        missing_message="Missing diagnostic component",
    )


def write_diagnostic(output: Path = OUTPUT) -> None:
    ahk_bundle.write_bundle(build_diagnostic_text(), output)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the standalone Viewer context diagnostic.")
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help="Destination for the generated standalone AHK.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    write_diagnostic(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
