#!/usr/bin/env python3
"""Build the single-file MxNM Lung montage field test."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from scripts import ahk_bundle
except ModuleNotFoundError:  # executed directly from scripts/
    import ahk_bundle


ROOT = ahk_bundle.ROOT
DIRECTIVES = ahk_bundle.HARNESS_DIRECTIVES
read_component = ahk_bundle.read_component
OUTPUT = ROOT / "tests/windows/generated/mxnm_montage_lung_field_test_standalone.ahk"

COMPONENTS = (
    "src/Lib/UIA.ahk",
    "tests/windows/mxnm_montage_lung_field_test.ahk",
)

HEADER = (
    '; Generated single-file Windows field test.',
    '; Edit source components and rebuild; do not edit this file.',
    '; Operator-stepped Lung montage test; one action per hotkey.',
    ';@Ahk2Exe-SetFileVersion 0.7.0.0',
    ';@Ahk2Exe-SetProductVersion 0.7.0',
    ';@Ahk2Exe-SetName MxNM Montage Lung Field Test',
)


def build_field_test_text(root: Path = ROOT) -> str:
    return ahk_bundle.bundle(
        HEADER,
        COMPONENTS,
        root=root,
        label="field test",
        missing_message="Missing field-test component",
    )


def write_field_test(output: Path = OUTPUT) -> None:
    ahk_bundle.write_bundle(build_field_test_text(), output)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the standalone MxNM Lung montage field test.")
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help="Destination for the generated standalone AHK.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    write_field_test(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
